deployment:
  order: [mongodb,nrf,udr,udm,ausf,nssf,amf,pcf,upf,smf]
  config:
    mongodb:
      executable: /usr/bin/mongod
      #make sure to edit mongodb.conf so bind addr matches sba address
      config: /etc/mongodb.conf
    free5gc:
      executableDir: "../free5gc/bin"
      configDir: "../free5gc/config"

predeployment:
  ovs:
      bridgeName: ovs1
  network:
    cidr: 24
  services:
    - name: mongodb
      namespace: mongodb
      interfaces:
        sba:
          name: sba
          address: 10.0.123.100
    - name: nrf
      namespace: nrf
      interfaces:
        - name: sba
          address: 10.0.123.1
    - name: udr
      namespace: udr
      interfaces:
        - name: sba
          address: 10.0.123.2
    - name: udm
      namespace: udm
      interfaces:
        - name: sba
          address: 10.0.123.3
    - name: ausf
      namespace: ausf
      interfaces:
        - name: sba
          address: 10.0.123.4
    - name: nssf
      namespace: nssf
      interfaces:
        - name: sba
          address: 10.0.123.5
    - name: amf
      namespace: amf
      interfaces:
        - name: sba
          address: 10.0.123.6
        - name: n2
          address: 10.0.124.1
    - name: pcf
      namespace: pcf
      interfaces:
        sba:
          name: sba
          address: 10.0.123.7
    - name: upf
      namespace: upf
      interfaces:
        sba:
          name: sba
          address: 10.0.123.8
    - name: smf
      namespace: smf
      interfaces:
        sba:
          name: sba
          address: 10.0.123.9
    - name: host
      namespace: root
      interfaces:
        sba:
          name: sba
          address: 10.0.123.200
