deployment:
  config:
    mongodb:
      executable: /usr/bin/mongod
      #make sure to edit mongodb.conf so bind addr matches sba address
      config: /etc/mongodb.conf
    free5gc:
      executableDir: "../free5gc/bin"
      configDir: "../free5gc/config"
    logging:
      directory: "logs"

envConfig:
  network:
    cidr: 24
    ovs:
      bridge: ovs1
  services:
    - name: mongodb
      namespace: mongodb
      interfaces:
        - name: sba
          address: 10.0.123.100
      deploy: true
    - name: nrf
      namespace: nrf
      interfaces:
        - name: sba
          address: 10.0.123.1
      deploy: true
    - name: udr
      namespace: udr
      interfaces:
        - name: sba
          address: 10.0.123.2
      deploy: true
    - name: udm
      namespace: udm
      interfaces:
        - name: sba
          address: 10.0.123.3
      deploy: true
    - name: ausf
      namespace: ausf
      interfaces:
        - name: sba
          address: 10.0.123.4
      deploy: true
    - name: nssf
      namespace: nssf
      interfaces:
        - name: sba
          address: 10.0.123.5
      deploy: true
    - name: amf
      namespace: amf
      interfaces:
        - name: sba
          address: 10.0.123.6
        - name: n2
          address: 10.0.124.1
      deploy: true
    - name: pcf
      namespace: pcf
      interfaces:
        - name: sba
          address: 10.0.123.7
      deploy: true
    - name: upf
      namespace: upf
      interfaces:
        - name: n3
          address: 10.0.130.1
        - name: n4
          address: 10.0.140.1
      deploy: true
    - name: smf
      namespace: smf
      interfaces:
        - name: sba
          address: 10.0.123.9
        - name: n4
          address: 10.0.140.2
      deploy: true
    - name: host
      namespace: root
      interfaces:
        - name: sba
          address: 10.0.123.200
      deploy: false
