deployment:
  config:
    mongodb:
      executable: /usr/bin/mongod
      #make sure to edit mongodb.conf so bind addr matches sbi address
      config: ./config/mongodb.conf
    free5gc:
      executableDir: "../free5gc/bin"
      configDir: "./config"
      webconsole:
        publicDir: ../free5gc/webconsole/public
    logging:
      directory: "./logs"

envConfig:
  network:
    cidr: 24
    bridge:
      name: br1
    disableIpv6: true
    nat:
      - upfName: upf
        sourceCidr: 10.60.0.0/16
        destinationIfc: n6-0
      - upfName: upf
        sourceCidr: 10.61.0.0/16
        destinationIfc: n6-1

  services:
    - name: mongodb
      namespace: mongodb
      interfaces:
        - name: sbi
          address: 10.0.123.100
      deploy: true
    - name: nrf
      namespace: nrf
      interfaces:
        - name: sbi
          address: 10.0.123.1
      deploy: true
    - name: udr
      namespace: udr
      interfaces:
        - name: sbi
          address: 10.0.123.2
      deploy: true
    - name: udm
      namespace: udm
      interfaces:
        - name: sbi
          address: 10.0.123.3
      deploy: true
    - name: ausf
      namespace: ausf
      interfaces:
        - name: sbi
          address: 10.0.123.4
      deploy: true
    - name: nssf
      namespace: nssf
      interfaces:
        - name: sbi
          address: 10.0.123.5
      deploy: true
    - name: amf
      namespace: amf
      interfaces:
        - name: sbi
          address: 10.0.123.6
        - name: n2
          address: 10.0.124.1
      deploy: true
    - name: pcf
      namespace: pcf
      interfaces:
        - name: sbi
          address: 10.0.123.7
      deploy: true
    - name: upf
      namespace: upf
      interfaces:
        - name: n3
          address: 10.0.130.1
        - name: n4
          address: 10.0.140.1
        - name: n6-0
          address: 10.1.0.1
        - name: n6-1
          address: 10.1.1.1
      deploy: true
    - name: smf
      namespace: smf
      interfaces:
        - name: sbi
          address: 10.0.123.9
        - name: n4
          address: 10.0.140.2
      deploy: true
    - name: webconsole
      namespace: webc
      interfaces:
        - name: sbi
          address: 10.0.123.201
      deploy: true
    - name: host
      namespace: root
      interfaces:
        - name: sbi
          address: 10.0.123.200
      deploy: false
    - name: gnb
      namespace: gnb
      interfaces:
        - name: rl
          address: 10.0.200.1
        - name: n2
          address: 10.0.124.2
        - name: n3
          address: 10.0.130.2
      deploy: false
    - name: ue
      namespace: ue
      interfaces:
        - name: rl
          address: 10.0.200.2
      deploy: false
    - name: internet
      namespace: internet
      interfaces:
        - name: n6
          address: 10.1.0.2
      deploy: false
    - name: internet2
      namespace: internet2
      interfaces:
        - name: n6
          address: 10.1.1.2
      deploy: false

